### ISSUE TITLE
ISO 3166-1 alpha3 Country Codes?

### ISSUE THREAD

**Issue by lurraca** [stefanpenner/country_select#100]
Is there a way to use the ISO 3166-1 alpha3 country codes from the [countries gem](https://github.com/hexorx/countries/)? if not, is this something that you would like to see implemented in this gem?

**Comment by scudco** [comment]
yeah, that's actually a worthwhile feature I think we could turn on via configuration. Right now we've got a way to format the option text that is generated, but perhaps we should also have a way to format the values themselves. Maybe something like having the `FORMATS` lambdas able to return an array that plays nicely with Rails' option tag helpers.

```ruby
# config/initializers/country_select.rb
CountrySelect::FORMATS[:alpha3] = lambda do |country|
  [  country.name, country.alpha3 ]
end
```

```erb
country_select("user", "country", format: :alpha3)
```

This kind of functionality would also give 1.x users a cleaner upgrade path to 2.x. I think it's a good idea.

**Comment by lurraca** [comment]
@scudco I will like to submit a PR for this.

**Comment by scudco** [comment]
Awesome, PR would definitely be welcome :smiley:

**Comment by marknatera** [comment]
@scudco how would you store the alpha3 country codes in your model? When a user selects a country he sees the the alpha3 code, but when entered in the database it stores the alpha2 country code.

**Comment by scudco** [comment]
This feature isn't implemented yet. The code example above was a suggestion for the PR.

**Comment by lurraca** [comment]
Finally had some time to tackle this. Let me know if there any improvements that could be made.
