### ISSUE TITLE
High memory consumption

### ISSUE THREAD

**Issue by zywx** [stefanpenner/country_select#107]
Using http://engineering.heroku.com/blogs/2015-08-06-patching-rails-performance/

country_select consumes 26M, mostly because of iso3166.

**Comment by stefanpenner** [comment]
Although this affects country_select, I believe the source of the issue is https://github.com/hexorx/countries/

**Comment by dgilperez** [comment]
Countries gem just released a new version to address this issue: https://github.com/hexorx/countries/pull/285

They hit 1.0, with a few major changes, so we cannot use it directly with current version of `country_select`

**Comment by scudco** [comment]
Fixed by #108

**Comment by zywx** [comment]
Well done!
