### ISSUE TITLE
Plug for subdivision_select

### ISSUE THREAD

**Issue by cllns** [stefanpenner/country_select#112]
A few months ago I made a Rails engine that leverages `country_select` to automatically load (via AJAX) the subdivisions (states/provinces) into another select box. It's called [`subdivision_select`](https://github.com/cllns/subdivision_select).

Would you be open to adding a shameless plug for that project in the README for this repo? It could be useful to other `country_select` users.

I can open a PR, provided you think this is a good idea.  I totally understand if you don't want to though :)

**Comment by scudco** [comment]
I think this fits in nicely with `country_select` and would be happy to add a note to end of the README. 

Given that subdivision data is contained in the `countries` gem, I'd really like to see a vanilla, non-ajax `subdivision_select` live here in `country_select` in some future version.

Would you open to contributing that here? `country_select` would have a wider baseline functionality for  ISO3166 standards and your engine could layer on the ajax functionality for those that need it.

**Comment by cllns** [comment]
Cool! 

How would you want to approach that? By loading one JS/JSON file on load that has all the data we need?

**Comment by scudco** [comment]
just an implementation of your `subdivision_select` helper that statically loads the subdivisions based on a country code

```
<%= subdivision_select :state, country_code: 'US' %>
```

then maybe the engine could support ajaxifying a subdivision select based purely off of a `data` attribute on the `select` tag

```
<%= country_select :country_code %>
<%= subdivision_select :subdivision, update_from: :country_code %>
```

which might produce

```
<select id="country_code" name="country_code">
...
</select>
<select id="subdivision" name="subdivision" data-country-code-field="country_code">
...
</select>
```

The engine could automatically pick up on that `data-country-code-field` attribute to automatically update the options when the selected `country_code` changes.

**Comment by cllns** [comment]
It actually already statically loads subdivisions, with this syntax 
```
<%= subdivision_select :state, 'US' %>
```
I could change it to `country_code:` or `country:` though, if you think that's better.

I do like the approach of using a data attribute, rather than my current class-based technique. I thought it'd be easier to just do it by proximity, but manually specifying which `<select>` to update from makes more sense!

**Comment by scudco** [comment]
Closing this due to age, but there are some really cool feature ideas in here I wish I had time for.
