### ISSUE TITLE
How to disable the field?

### ISSUE THREAD

**Issue by omarwaleed** [stefanpenner/country_select#115]
i tried this but it didnt work
```
<%= f.country_select :nationality, class: "fields", :priority_countries => ["EG", "SA", "AE","JO"], :prompt => "Your nationality", :disabled => true %>
```
the fields are still editable. what should i do?

**Comment by scudco** [comment]
You'll need to wrap the country_select options in an explicit hash.

Here is an example of HTML attributes and country_select options:

https://github.com/scudco/country_select_test/blob/master/app/views/welcome/_vanilla_form.html.erb#L31

**Comment by omarwaleed** [comment]
it worked thank you. as you said i had to enclose the options in a hash and put the disabled option outside that hash. also i had to reorder the option fields. the country_select options hash had to come right after the naming and so the class option had to be moved to the end of the line.
closing issue
