### ISSUE TITLE
Is it possible to authorize in gemspec countries 1.2.X

### ISSUE THREAD

**Issue by ldonnet** [stefanpenner/country_select#116]
Hi,

I need to update my translations for countries and get the last version. If you could authorize in gemspec higher version it could be great!!

Thanks 
Luc Donnet

**Comment by scudco** [comment]
Done, you should be able to use `country_select` v2.5.0

Thanks for letting me know they had released a new version.

Out of curiosity, what feature did you need from `countries` v1.2.x?

**Comment by ldonnet** [comment]
Don't need really a feature but updated translations in the gem.
Thanks a lot!
