### ISSUE TITLE
Superclass mismatch for class Country

### ISSUE THREAD

**Issue by jonian** [stefanpenner/country_select#118]
Hi,
Using `require 'countries/global'` in `country_select/lib/country_select.rb` causes this conflict in version 2.5.0, if you already have a County model.

I think you should use `require 'countries/iso3166'`, like in the 2.4.0 version which did not cause this conflict.

https://github.com/hexorx/countries/tree/master/lib/countries

**Comment by scudco** [comment]
Thanks for pointing this out @jonian. I misread the upgrade guide for `countries`, and I believe they removed that file (`countries/iso3166`). Using a simple `require "countries"` works as expected now.

I've released v2.5.1. Let me know if that solves your issue.

**Comment by jonian** [comment]
Yes, it solves the issue.
Thank you for the quick response and fix!
