### ISSUE TITLE
When you hover over an option and click away, option still gets selected

### ISSUE THREAD

**Issue by JoannaFalkowska** [stefanpenner/country_select#119]
It's not a default behaviour for dropdown selects. When you open a select box, hover, and then click away from it, previous option should still be selected, not the one you last hovered over.

**Comment by scudco** [comment]
I can't reproduce this. Even if I could, I'm not sure how `country_select` could be generating `select` and `option` tags that would produce this kind of behavior.

You're welcome to re-open this issue and post a screen recording here to show me what is happening. Here's one of me trying to do this in Chrome:

![country_select](https://cloud.githubusercontent.com/assets/3806/11959105/9338b276-a899-11e5-9fc9-cc755a40de2b.gif)
