### ISSUE TITLE
doc for blank value.

### ISSUE THREAD

**Issue by ranska** [stefanpenner/country_select#120]
add somewhere in the doc, the ```include_blank``` option.

```ruby
:include_blank => 'Please choose...'
```

**Comment by scudco** [comment]
https://github.com/stefanpenner/country_select/commit/c83c550e3e4585c3e9c1b749df65619428aa985d

If you want more examples check out the [example app view files](https://github.com/scudco/country_select_test/tree/master/app/views/welcome) linked in the README
