### ISSUE TITLE
How to add additional language support? 

### ISSUE THREAD

**Issue by imgarylai** [stefanpenner/country_select#121]
Hi, 
I want to add Chinese (both simplified and traditional) support to this gem but I'm not sure where should I get start first. 

I also read this repository: [hexorx/countries](https://github.com/hexorx/countries) to figure out how it works. I try to use Japnese as an example but I can't find the `ja` translation file, either. I still don't understand how this gem works. I would appreciate that anyone give me any hint or instruction.

**Comment by imgarylai** [comment]
I think I should write down what I did. 

I noticed this gem support Japanese and I want to add Chinese support this gem as well. 

I took Japanese as an example. First, I tried to find out translation files and I did find where Japanese place. For example, in this file: https://github.com/hexorx/countries/blob/master/lib/countries/data/countries/TW.yaml, I could find Japanese in names. However, how did this gem map locale to `:ja`?

**Comment by rposborne** [comment]
@imgarylai Come file a request over at https://github.com/hexorx/countries. But regardless we extract translations from upstream [debian packages](http://anonscm.debian.org/cgit/pkg-isocodes/iso-codes.git/),  but we have a facility to add / alter the data if we are unable to push a patch up.   See our [translations override file](https://github.com/hexorx/countries/blob/master/lib/countries/data/translation_corrections.yaml)  We are all ears to getting the most complete dataset we can.

**Comment by scudco** [comment]
Thanks for answering this @rposborne 

I wasn't sure what to say ;)
