### ISSUE TITLE
Activate rails 3 country select

### ISSUE THREAD

**Issue by ldonnet** [stefanpenner/country_select#122]
Hi, 

I have got an error with a Rails app version 3.2.22 with formtastic 3.1.3 + formtastic_bootstrap 3.1.1 + country_select 2.5.1 with country input : wrong number of arguments (4 for 0).

I check the code in lib/country_select.rb and I see this code : 

``` ruby
if defined?(ActionView::Helpers::Tags::Base)
  require 'country_select/country_select_helper'
else
  require 'country_select/rails3/country_select_helper'
end
```

But when I test in rails console I have : 

``` sh
Loading development environment (Rails 3.2.22)
[1] pry(main)> defined?(ActionView::Helpers::Tags::Base)
=> "constant"
```

The rails select helper loaded seems to be the wrong one for my rails version. Perhaps the test must be updated?

Best Regards
Luc Donnet

**Comment by ldonnet** [comment]
Perhaps this way : 

if Rails::VERSION::MAJOR = 3
  # Do the old thing
else
  # Do it the new way
end

**Comment by scudco** [comment]
hmm, yeah perhaps it should be updated. I have a vague memory of choosing not to go down that path, but now I can't remember why. 

I'm wondering what your Gemfile looks like. What I've found is some gems open up that module/class path (`ActionView::Helpers::Tags::Base`) regardless of which version of rails it's running on.

So you can get up and running right now, I'd recommend adding `require: false` to your Gemfile and creating a rails initializer that looks like:

```ruby
require 'countries'
require 'sort_alphabetical'

require 'country_select/version'
require 'country_select/formats'
require 'country_select/tag_helper'

#if defined?(ActionView::Helpers::Tags::Base)
  #require 'country_select/country_select_helper'
#else
  require 'country_select/rails3/country_select_helper'
#end
```

A pain, but at least you can get going until I can fix this.

**Comment by ldonnet** [comment]
Thanks for your help and your time!

**Comment by ArnoHolo** [comment]
I've had the same issue and I created a rails initializer like you suggested @scudco, which worked for me. Thank you!

**Comment by scudco** [comment]
Not an ideal situation here, but I'm closing this because I won't be spending any time fixing Rails 3 issues since a workaround exists.
