### ISSUE TITLE
How to filter by 'no country'??

### ISSUE THREAD

**Issue by miguelfg** [stefanpenner/country_select#123]
How can I add an option in the country selector for those records in my db that has the country column as NULL??

**Comment by scudco** [comment]
I think you want to add `include_blank: true`. Something like

```
country_select("user", "country", include_blank: true)
```

**Comment by miguelfg** [comment]
Thanks, you show me the way, I've ended up using: 
     prompt: 'Filter by country'
instead of include_blank. Prompt option, adds a new option with value equal to  "". Same as include_blank, however this one leaves the text also blank.

**Comment by scudco** [comment]
Good call. Glad it worked.
