### ISSUE TITLE
alter country collection (add one country)

### ISSUE THREAD

**Issue by naaano** [stefanpenner/country_select#126]
I need to record when no country information is known, but can't find how to attach an extra fake country. 
It's not the same as leaving it nil, as there's is a difference between "form not filled" than "confirmed that is not known". 

Any ideas on how to address this?

thanks

**Comment by crucibond** [comment]
This will be of interest to you.

https://github.com/jameseunson/country_select

**Comment by naaano** [comment]
thank you!

**Comment by brentluna** [comment]
@naaano How did you go  about solving this? Am I missing something  about that fork? It looks identical.

**Comment by naaano** [comment]
I changed it on my fork, so you can set that through the options
