### ISSUE TITLE
Make dependency on `sort_alphabetical` optional?

### ISSUE THREAD

**Issue by fschwahn** [stefanpenner/country_select#128]
This gem depends on `sort_alphabetical`, which in turn depends on `unicode_utils`, which has some problems with memory consumption & load time (see https://github.com/lang/unicode_utils/issues/6). Is it possible to make the dependency on `sort_alphabetical` optional, require it when present, but fall back to a normal sort when not?

I'd put together a PR if you think that's worthwhile.

**Comment by scudco** [comment]
I would be open to a PR for this since it appears unicode_utils is not addressing this performance problem.

If possible, I'd like to see this work by changing the `require` option in a Gemfile

```
gem 'country_select', require: 'country_select_without_unicode_utils'
```

**Comment by lurchpop** [comment]
it would also be cool to see the nokogiri dependency removed.
