### ISSUE TITLE
Initialize Without Model?

### ISSUE THREAD

**Issue by julianwilson** [stefanpenner/country_select#130]
I'd like to be able to whitelist my form parameters, and currently as the "model" parameter is required first it is sending the country POST var in a child JSON object, such as ""charge"=>{"country"=>"US"}". Is there anyway to just have it use "country" => "US"?

Thanks!

**Comment by gtournie** [comment]
+1 👍

**Comment by scudco** [comment]
ah, yeah we need to probably add `country_select_tag` 

Sorry I missed this when it was originally created.

**Comment by Sprachprofi** [comment]
Please add country_select_tag and options_for_select

**Comment by Leo137** [comment]
Monkey patch to add country_select_tag functionality:

`config/initializers/country_select_tag_fix.rb`

```
module ActionView
  module Helpers
    module FormOptionsHelper
      def country_select_tag(method, options = {}, html_options = {})
        tags = Tags::CountrySelect.new(nil, method, self, options, html_options).country_option_tags
        select_tag(method, tags, html_options)
      end
    end
  end
end
```

**Comment by scudco** [comment]
closing due to lack of feedback
