### ISSUE TITLE
Priority countries showing "priority countries" instead of options

### ISSUE THREAD

**Issue by ssoulless** [stefanpenner/country_select#132]
I have a form and when I add the following:

`country_select :user, :country, priority_countries: ["CH","DE"]`
The select shows:

```
priority countries
-----------------------
Afganistan
The countries here
.....
```

it is showing the "priority Countries" text instead of the countries it should be showing....

**Comment by scudco** [comment]
This looks like maybe you're trying to use 2.x syntax on an older version of the gem, though I can't be sure. Check out the upgrade guide https://github.com/stefanpenner/country_select/blob/master/UPGRADING.md
