### ISSUE TITLE
Cant Not Install Gem

### ISSUE THREAD

**Issue by dahlia05** [stefanpenner/country_select#133]
gem 'country_select'

I think this gem no longer install stefanpenner/country_select. Therefore I was getting version 1.1.5 instead of 2.5.1. And I also  get the  WrongArgument Exception

Therefore I changed in Gem File  to get the correct one
gem 'country-select', github: 'stefanpenner/country_select'

However When I am running 'bundle install'. I am getting the following response

Fetching git://github.com/stefanpenner/country_select.git
Fetching gem metadata from https://rubygems.org/
Fetching version metadata from https://rubygems.org/
Fetching dependency metadata from https://rubygems.org/
Could not find gem 'country-select x86-mingw32' in
git://github.com/stefanpenner/country_select.git (at master@46548db).
Source does not contain any versions of 'country-select x86-mingw32'

Process finished with exit code 7

I have tried to delete GemLock file and run the bundle install again however nothing helped so far.
Please suggest me how can I solve this problem.

**Comment by scudco** [comment]
You'll need to specify which version of the gem you want in your Gemfile. It's a good idea to _not_ use versions directly from github.

Try something like: `gem 'country_select', '~> 1.1.3'` if you're looking for an older version.
