### ISSUE TITLE
In rails 4 the country select form builder is not working

### ISSUE THREAD

**Issue by charlesskariah** [stefanpenner/country_select#134]
When trying to add the form builder,
= f.country_select :country_of_birth, ["United States"], {}, { :class => "form-control" }
It's throwing an error, i tried couple of solutions and none of them worked for me
Is there a compatibility issue for this gem with rails 4.+?

**Comment by scudco** [comment]
@charlesskariah this looks similar to #151. The example you provided doesn't appear to be valid `country_select` syntax. Check out https://country-select-test.herokuapp.com/
