### ISSUE TITLE
Dependency sixarm_ruby_unaccent missing

### ISSUE THREAD

**Issue by morgler** [stefanpenner/country_select#139]
I got an error when trying to start the server after installing this gem:

`cannot load such file -- sixarm_ruby_unaccent (LoadError)`

After adding the https://github.com/SixArm/sixarm_ruby_unaccent gem to my Gemfile explicitly, it worked.

**Comment by scudco** [comment]
Is this something that was related to your specific application? If this is a problem that you can explain further, please re-open this issue.

**Comment by mmzoo** [comment]
Just ran into the same thing. This was an upstream issue causes by [this require](https://github.com/hexorx/countries/blob/master/lib/countries.rb#L2) in the [countries gem](https://github.com/hexorx/countries).

Has been fixed as of `2.0.8` as per [this commit](https://github.com/hexorx/countries/commit/6a84b6e1446e38ae6a06b8bbbbffe910342f7c02).

End users should run `bundle update countries` to fix this. A mere `bundle update country_select` will not suffice.

**Comment by imi56** [comment]
Still facing the issue:
```
>> gem list | grep countries
countries (2.0.1, 0.11.5, 0.10.0)
>> gem list | grep country_select
country_select (3.1.1, 2.1.0)
```

**Comment by scudco** [comment]
@imi56 can you try upgrading `countries` to >= 2.0.8 as @mmzoo recommended?

**Comment by dylan-chong** [comment]
Adding this to Gemfile solved the problem for me

```ruby
gem 'sixarm_ruby_unaccent' # Needed to fix: `LoadError: cannot load such file -- sixarm_ruby_unaccent` caused by countries/country_select
```
