### ISSUE TITLE
country_select: how to add countries' attributes as HTML data?

### ISSUE THREAD

**Issue by sepastian** [stefanpenner/country_select#142]
Hello,

I'm using country select to populate a `select` field. When the user selects a country, I would like to set the value of another field, `telephone`, to the country code using JS.

For this to work, I would like to add a `data` attribute containing the country code to each `option` field. What I need is this:

`<option value="AT" data-code="43">`

Is is possible to set add a data attribute when calling `country_select`?

Thanks!

**Comment by scudco** [comment]
I don't think that'd be possible through any publicly accessible API of `country_select`. I have no idea what support for this might look like, but I'd gladly welcome any PRs that explore this further.

If you feel you're up for it, check out https://github.com/stefanpenner/country_select/blob/master/lib/country_select/tag_helper.rb#L4 and https://github.com/stefanpenner/country_select/blob/master/lib/country_select/tag_helper.rb#L77

Essentially, the option tags are created by passing arrays to ActionPack's built-in `options_for_select` and this code is pretty tightly coupled at the moment.

**Comment by scudco** [comment]
Thanks to @dcangulo for jogging my memory that this is indeed possible using custom formatters as explained here https://github.com/stefanpenner/country_select/pull/156#issuecomment-413887534

Essentially you just need to define a custom formatter in an initializer. Something like:
```ruby
# config/initializers/country_select.rb
CountrySelect::FORMATS[:with_data_attrs] = lambda do |country|
  [
    country.name,
    country.alpha2,
    {
      'data-country-code' => country.country_code,
    }
  ]
end
```

See https://country-select-test.herokuapp.com/ for a working example.
