### ISSUE TITLE
Ability to display only actual stricto sensu countries

### ISSUE THREAD

**Issue by gemp** [stefanpenner/country_select#149]
Is there a possibility to display only actual countries, without territories like Guam which country is the United-States, New Caledonia which country is France and so on?

Well, I guess not otherwise it would be indicated in the documentation... but that would be handy :)

**Comment by gemp** [comment]
For anyone interested, here is the 53 not sovereign countries:
```
country_select("user", "country", except: %w( AI AQ AS AW AX 
       BL BM BQ BV CC CK CW CX EH FK FO GF GG GI GL GP GS GU 
       HK HM IM IO JE KY MF MO MP MQ MS NC NF NU PF PM PN PR 
       PS RE SH SJ SX TC TF TK UM VG VN WF ))
```
Note: You can remove "PS" from the list if you're inclined to think Palestine is an actual country...

**Comment by scudco** [comment]
Thanks for adding that example @gemp 

As stated in the [README](https://github.com/stefanpenner/country_select#rails--country-select) this gem aims to use an ISO standard to avoid having any opinions on these matters.

A good short-term solution might be to define the excepted country codes in a constant in an initializer. A longer term feature-based solution might be to allow a global setting for `country_select`. I would certainly consider PRs that added a pattern to the README or added a global setting feature.

Alternatively, are you aware of any standardized list that those 53 country codes might belong to? If we could use a standardized categorization, then I'd be even more inclined to find a good way to integrate those country code lists.

`country_select("user", "country", include_all: true)`
`country_select("user", "country", exclude_<standardized_name_of_53_country_codes>: true)`

or in an initializer:

`CountrySelect.default_country_codes_list = :<name_of_grouping_of_countries>`

I think it would be great to have official lists of country codes within this gem. Something like `:eu_countries` which would only load...EU countries, `:<continent_name>_countries`, etc. Ultimately, I still would only want to allow groupings that are maintained by an external standards body, but adding this feature would get the gem closer to explicitly supporting what you're talking about.

**Comment by gemp** [comment]
Thanks for your comment @scudco 

In fact, painfully doing the list of not-so-sovereign-countries by hand, based on [some Wikipedia info](https://en.wikipedia.org/wiki/List_of_sovereign_states), I realised why the the gem has no such option and why you're perfectly right when you state "to avoid having any opinions on these matters".

It's a frigging complicated matter, to say the least. Firstly because some sovereignties are disputed. Secondly because borders change pretty much all the time.

And for maintainability sake, it seems better to do this by hand, as I did. Just to remember, whenever a country needs to be added (let's say Palestine or Catalonia which might be sooner), that some other might have disappeared (maybe Taiwan). Adding is cool, removing will give some shitty bugs... That's why I also freezed the gem version.

Our job would be simpler if the world was a little bit more stable 😅

PS: I updated the list above to correct some mistakes.

**Comment by scudco** [comment]
That is a very helpful wikipedia page.

In a future version, I do want to find a way to maintain useful groupings of countries. I'd certainly consider `:un_member_countries` as a valid and useful grouping. 

I'm going to close this issue, but feel free to re-open if you (or anyone reading this) has more to add.
