### ISSUE TITLE
Rails 5.2 Compatibility

### ISSUE THREAD

**Issue by kevinjbayer** [stefanpenner/country_select#151]
Trying to upgrade to Rails 5.2 and this gem is giving me some issues. I'm hitting an ArgumentError that's showing: wrong number of arguments (given 1, expected 0)

The line of code that's throwing it is `<%= f.country_select :country_code, %w(US CA), {prompt: 'Please select a country'}, :class => 'form-control' %>`

Tried pointing to  gem 'country_select', github: 'stefanpenner/country_select', still with no luck. Anyone get this working with 5.2?

**Comment by scudco** [comment]
I’ll take a look. I don’t think this was tested with 5.2 yet.

**Comment by scudco** [comment]
@kevinjbayer I've updated the build and test app to use Rails 5.2 https://github.com/scudco/country_select_test 

However, I just noticed you may have been using an old version of `country_select` that ended up being upgraded when you upgraded Rails. The example you provided doesn't appear to be valid `country_select` syntax with the latest version. Please check out the examples on https://country-select-test.herokuapp.com/ If this is the case, also take a look at https://github.com/stefanpenner/country_select/blob/master/UPGRADING.md

**Comment by kevinjbayer** [comment]
@scudco I'm an idiot. Your note about upgrading made me go back and look through what I was using. Apparently, I just added this gem in while I was upgrading because I _thought/assumed_ I was using it, because I remember looking at it before. It turns out the country_select that I'm using is coming from the carmen-rails gem, and not this one. The methods look somewhat similar, so I'm hoping to use your work here to diagnose what's wrong over there.

If I can send you a couple bucks to buy you a beer for wasting your time on a Sunday, I'd be happy to. My apologies.

**Comment by scudco** [comment]
don't sweat it. glad you got it figured out 👍
