### ISSUE TITLE
Collection along with priority not working for country_select v3.1.1

### ISSUE THREAD

**Issue by meenakshikumari** [stefanpenner/country_select#154]
I have upgraded versions of:
rails from 4.1.10 to 5.2.0 
ruby from 2.1.0 to 2.5.1
country-select from 1.2.0 to 3.1.1
database from mongodb to postgres.

In my previous code, a simple form drop down containing collections `VALID_COUNTRIES = CountrySelect::COUNTRIES_FOR_SELECT.collect(&:titleize)` of countries with priority given to Australia and New Zealand.
Previous code: `a.input :country, input_html: { id: "country_#{a.object.type.underscore.gsub(' ', '_')}" }, priority: ["", "Australia", "New Zealand" ]`

 Now in my upgraded code this code didn't worked (because of country select gem update). Now i'm using collections `VALID_COUNTRIES = ISO3166::Country.all.collect(&:name).sort` only countries are displayed in sorted order, but priority are not working.

**Comment by scudco** [comment]
It looks like you jumped two major versions in one go. I'd recommend taking a look at the Upgrade Guide linked in the README.md https://github.com/stefanpenner/country_select#upgrading

**Comment by meenakshikumari** [comment]
Thanks. I read UPGRADING.md. It's mentioned their that the support for priority with simple-form has been removed from country-select version 3.0 . I had to manually code priorities in my code to match my previous code drop down. But why this support is removed? Just wanted to know the reason.

**Comment by scudco** [comment]
Priority Countries using country names in `simple_form` was removed in 3.0, but you you can still specify the priority of a `simple_form` country select. See: https://github.com/scudco/country_select_test/blob/master/app/views/welcome/_simple_form_form.html.erb#L8 and http://country-select-test.herokuapp.com

The most important change from 1.x to 2.x is switching from country names to country codes. You'll need to migrate your data to use country codes if you want to use country_select 2+.

**Comment by meenakshikumari** [comment]
Yeah i tried this it worked, but along with collection in the simple form this thing is not working. so i have to manually manipulate my code to get it done.
