### ISSUE TITLE
[ERROR] wrong number of arguments (given 1, expected 0)

### ISSUE THREAD

**Issue by dcangulo** [stefanpenner/country_select#155]
I have an issue using this gem.

## Steps to reproduce:
1. Terminal: `rails new trialapp`
2. Terminal: `cd trialapp`
3. Terminal: `rails g model User`
4. In `db/migrate/xxxxx_create_users.rb` add the following:
```ruby
...
t.string :username
t.string :country_code
...
```
5. Terminal: `rake db:migrate`
6. Terminal: `rails g controller users`
7. In `config/routes.rb` add the following:
```ruby
...
resources :users
root 'users#new'
...
```
8. In `Gemfile` add the following:
```ruby
...
gem 'country_select'
...
```
9. Terminal: `bundle install`
10. In `app/views/users` create a new file `new.html.erb`
11. In `app/views/users/new.html.erb` add the following:
```ruby
<%= form_for User.new, url: root_url do |f| %>
  <%= f.country_select :country_code %>
<% end %>
```
12. Terminal: `rails s`
13. Open browser and enter `localhost:3000` in the address bar.

## Expected Output:
A form with a simple select dropdown containing countries.

## Actual Output:
```ruby
ActionView::Template::Error (wrong number of arguments (given 1, expected 0)):
    1: <%= form_for User.new, url: root_url do |f| %>
    2:   <%= f.country_select :country_code %>
    3: <% end %>
```

## Test Environment:
**Laptop:** MacBook Pro (Retina, 13-inch, Mid 2014)
**OS:** macOS High Sierra
**OS Version:** Version 10.13.4 (17E199)
**Ruby Version:** ruby 2.3.5p376 (2017-09-14 revision 59905) [x86_64-darwin17]
**Rails Version:**  Rails 5.2.1
**Browser:** Google Chrome
**Browser Version:** Version 68.0.3440.106 (Official Build) (64-bit)

**Comment by donBigote** [comment]
I just installed the gem in a new rails 5.2 app, and got the same error.

**Comment by dcangulo** [comment]
Okay, I managed to make it work.

In **Step 13** it will throw an error stated above.

## Solution:
Adding these steps solved the problem in my case.

14. Terminal: `bundle update`
15. Restart the rails server

## Question:
This isn't supposed to be the proper way to handle this right?

**Comment by dcangulo** [comment]
## UPDATE:

It seems like putting `gem 'country_select'` in the `Gemfile` and running `bundle install` will install version`country_select (2.5.2)`.

This version is the version that throws an error stated above.

Then running the **Steps 14** and **15** will solve the problem as this updates the gem to version `country_select (3.1.1)`.

**Comment by scudco** [comment]
This is definitely strange. I did some searching, and it looks like [bundler doesn't guarantee it will grab the latest version of a gem](https://github.com/bundler/bundler/issues/3089) if you leave the version unspecified. That was not my understanding or expectation of how bundler works. I think I'll update the README in the short term.

Thanks for looking into this.
