### ISSUE TITLE
CSS not applied to country select

### ISSUE THREAD

**Issue by le4ker** [stefanpenner/country_select#159]
Hi,

First of all thank you for the great gem 😊 

When I'm applying a CSS class according to your README I don't see it in the output HTML

```
<%= country_select(:investor, :nationality, { selected: @investor.nationality }, {class: 'select-input', required: true}) %>
```

Thank you,
:panos

**Comment by le4ker** [comment]
Hi @stefanpenner can you please have a look at this? The gem introduces a bug in the mobile responsiveness of our web app due to this issue and we would really like to keep the gem because it works like a charm apart from this bug. Thank you.

**Comment by scudco** [comment]
@le4ker Can you post what version of the gem and what version of Rails you're using?

**Comment by le4ker** [comment]
Thanks @scudco .

rails -v returns:

`Rails 5.1.6
`
and the Gemfile.lock contains:

```
country_select (3.1.1)
      countries (~> 2.0)
      sort_alphabetical (~> 1.0)
```

**Comment by scudco** [comment]
I just tested this in https://github.com/scudco/country_select_test and cannot get it to reproduce. Can you paste the resulting `<select>` tag that is being generated for you?

**Comment by le4ker** [comment]
I tried it again and now the class was rendered in the HTML. But I don't understand why it was working before, it was the exact same code. Anyway, @scudco thank you for the help!
