### ISSUE TITLE
How to instruct country select gem to attach only on specific attributes, not each one that consist country?

### ISSUE THREAD

**Issue by jerko-culina** [stefanpenner/country_select#168]
Not sure if this is the right place, sorry if it is not.

I noticed that country select gem attach himself on each form field that has a country in the name( or similar to that).

Just want to know if there is any way that I can instruct country select gem to attach on only specific attributes. 

Thanks!

**Comment by jerko-culina** [comment]
I figured out. Just need to add `as` option like in the example below:

`f.input :phone_country_code, as: :string`

**Comment by scudco** [comment]
@jerko-culina thanks for posting your findings here. Likely, the root cause is another gem (e.g., formtastic, simple_form). `country_select` doesn't do any magic around form inputs.
