### ISSUE TITLE
NoMethodError Error

### ISSUE THREAD

**Issue by ehsanatwork** [stefanpenner/country_select#169]
Hello
I am trying to add this on my app. but it is showing the following errors.
`NoMethodError in Admin::Cities#new `
`undefined method `country_code' for #<City:0x00007f1f64db2560>`

can any one please tell me where is the problem?

Thank you

**Comment by scudco** [comment]
Sorry for the delayed reply. I'd guess you don't have a `country_code` attribute on your `City` class. You'll need to invoke the `country_select` helper with an attribute that actually exists on your `City` object.
