### ISSUE TITLE
CI: Matrix updates needed

### ISSUE THREAD

**Issue by olleolleolle** [stefanpenner/country_select#178]
This Issue is about the Travis CI matrix.

In order to support Rails & Ruby versions in support, there needs to be some new matrix elements:

- [x] Gemfile for Rails 6.0
- [x] Gemfile for Rails 6.1
- [x] Exclusions for Rails+Ruby versions not compatible
- [x] Ruby 2.6
- [x] Ruby 2.7

**Comment by scudco** [comment]
https://github.com/stefanpenner/country_select/pull/172/commits/2f164425fab071ae4c539e535ca543adeb9748de in #172  should take care of these... though it looks like my updating of the gemfiles might mess something with `platform` directive in the gemfiles 🤦

**Comment by olleolleolle** [comment]
@scudco PS: Awesome that you were doing this, already!

**Comment by scudco** [comment]
thanks for all your help this week 👍

**Comment by olleolleolle** [comment]
🎉 Big congratulations on big merge!!! @scudco
