### ISSUE TITLE
Gemfile.lock & c: update to 5.0.0

### ISSUE THREAD

**Issue by olleolleolle** [stefanpenner/country_select#180]
This line sits at 5.0.0.pre

https://github.com/stefanpenner/country_select/blob/master/Gemfile.lock#L4

...but when a developer runs that at home, they get `5.0.0` and a diff.

Can we make it so that the committed Gemfile.lock (and other lockfiles) is up-to-date?

**Comment by scudco** [comment]
Fixed in 93fbae3

thanks for catching this. I only caught the travis lockfiles at first.
