### ISSUE TITLE
How can I add a CSS class to a select generated through country_select?

### ISSUE THREAD

**Issue by jlstr** [stefanpenner/country_select#55]
Hello, so I have this (In HAML):

= ad.country_select :country, [ "United States" ]

I haven't find a way to do somehting like this:

= ad.country_select :country, [ "United States" ], class: 'my-select-class'

Is this possible?

**Comment by le4ker** [comment]
Hi,

The css is not rendered when used according to the README:

```
          <%= country_select :investor, :nationality, select: @investor.nationality, required: true, {class: 'select-class'} %>

```
