### ISSUE TITLE
Unicode sorting

### ISSUE THREAD

**Issue by Carpetsmoker** [stefanpenner/country_select#78]
In the Dutch translation, `Ålandeilanden` is sorted last. I would expect the `Å` to be sorted as a normal `A` (although unicode sorting is [more complicated](http://www.unicode.org/reports/tr10/) than that, it certainly shouldn't expect it to be last).

A possible solution from [stackoverflow](http://stackoverflow.com/a/17173122/660921):

> To properly collate strings according to locale, the ffi-icu gem could be used:
> ```
> require "ffi-icu"
>
> ICU::Collation.collate("it_IT", %w[à a e])
> # => ["a", "à", "e"]
>
> ICU::Collation.collate("de", %w[a s x ß])
> # => ["a", "s", "ß", "x"]
> ```

**Comment by pnull** [comment]
:+1: sort_alphabetical is a very good solution. Your should go with that.

**Comment by scudco** [comment]
Fixed #97
