### ISSUE TITLE
undefined method `first' for nil:NilClass

### ISSUE THREAD

**Issue by rafrafgit** [stefanpenner/country_select#84]
Getting this error on this line:
```
/lib/country_select/tag_helper.rb:  68:in `block (2 levels) in country_options_for'
````

I have just introduced using i18n in my application, perhaps related?

**Comment by rafrafgit** [comment]
It happened again so I am reopening this. I run an ecommerce website and occationally customers come in and get this error. Happened today with a guy from the US

**Comment by rafrafgit** [comment]
stack trace:
Error message
ActionView::Template::Error: undefined method `first' for nil:NilClass

Sample stack trace (hide Rails)
…y_select-1d0d6358f041/lib/country_select/
tag_helper.rb:  68:in `block (2 levels) in country_options_for'
…y_select-1d0d6358f041/lib/country_select/
tag_helper.rb:  64:in `map'
…y_select-1d0d6358f041/lib/country_select/
tag_helper.rb:  64:in `block in country_options_for'
…p/vendor/bundle/ruby/2.1.0/gems/i18n-0.6.1/lib/
i18n.rb: 246:in `with_locale'
…y_select-1d0d6358f041/lib/country_select/
tag_helper.rb:  63:in `country_options_for'
…y_select-1d0d6358f041/lib/country_select/
tag_helper.rb:  10:in `country_option_tags'
…041/lib/country_select/rails3/
country_select_helper.rb:  34:in `render'
…041/lib/country_select/rails3/
country_select_helper.rb:  18:in `country_select'
/app/app/views/payments/_stripe_form.html.erb:173:in `block in _app_views_payments__stripe_form_html_erb___1430446013652768195_70103663585320'
…npack-3.2.13/lib/action_view/helpers/
capture_helper.rb:  40:in `block in capture'
…npack-3.2.13/lib/action_view/helpers/
capture_helper.rb: 187:in `with_output_buffer'
…npack-3.2.13/lib/action_view/helpers/
capture_helper.rb:  40:in `capture'
…pack-3.2.13/lib/action_view/helpers/
form_tag_helper.rb: 663:in `form_tag_in_block'
…pack-3.2.13/lib/action_view/helpers/
form_tag_helper.rb:  70:in `form_tag'
/app/app/views/payments/_stripe_form.html.erb:117:in `_app_views_payments__stripe_form_html_erb___1430446013652768195_70103663585320'
…1.0/gems/actionpack-3.2.13/lib/action_view/
template.rb: 145:in `block in render'
…tivesupport-3.2.13/lib/active_support/
notifications.rb: 125:in `instrument'
…1.0/gems/actionpack-3.2.13/lib/action_view/
template.rb: 143:in `render'
…ck-3.2.13/lib/action_view/renderer/
partial_renderer.rb: 265:in `render_partial'
…ck-3.2.13/lib/action_view/renderer/
partial_renderer.rb: 238:in `block in render'
…k-3.2.13/lib/action_view/renderer/
abstract_renderer.rb:  38:in `block in instrument'
…tivesupport-3.2.13/lib/active_support/
notifications.rb: 123:in `block in instrument'
….2.13/lib/active_support/notifications/
instrumenter.rb:  20:in `instrument'
…tivesupport-3.2.13/lib/active_support/
notifications.rb: 123:in `instrument'
…k-3.2.13/lib/action_view/renderer/
abstract_renderer.rb:  38:in `instrument'
…ck-3.2.13/lib/action_view/renderer/
partial_renderer.rb: 237:in `render'
…actionpack-3.2.13/lib/action_view/renderer/
renderer.rb:  41:in `render_partial'
…ack-3.2.13/lib/action_view/helpers/
rendering_helper.rb:  27:in `render'
/app/app/views/payments/enroll.html.slim:49:in `_app_views_payments_enroll_html_slim___2010845625016761305_70103653261660'
…1.0/gems/actionpack-3.2.13/lib/action_view/
template.rb: 145:in `block in render'
…tivesupport-3.2.13/lib/active_support/
notifications.rb: 125:in `instrument'
…1.0/gems/actionpack-3.2.13/lib/action_view/
template.rb: 143:in `render'
…k-3.2.13/lib/action_view/renderer/
template_renderer.rb:  47:in `block (2 levels) in render_template'
…k-3.2.13/lib/action_view/renderer/
abstract_renderer.rb:  38:in `block in instrument'
…tivesupport-3.2.13/lib/active_support/
notifications.rb: 123:in `block in instrument'
….2.13/lib/active_support/notifications/
instrumenter.rb:  20:in `instrument'
…tivesupport-3.2.13/lib/active_support/
notifications.rb: 123:in `instrument'
…k-3.2.13/lib/action_view/renderer/
abstract_renderer.rb:  38:in `instrument'
…k-3.2.13/lib/action_view/renderer/
template_renderer.rb:  46:in `block in render_template'
…k-3.2.13/lib/action_view/renderer/
template_renderer.rb:  54:in `render_with_layout'
…k-3.2.13/lib/action_view/renderer/
template_renderer.rb:  45:in `render_template'
…k-3.2.13/lib/action_view/renderer/
template_renderer.rb:  18:in `render'
…actionpack-3.2.13/lib/action_view/renderer/
renderer.rb:  36:in `render_template'
…actionpack-3.2.13/lib/action_view/renderer/
renderer.rb:  17:in `render'
…actionpack-3.2.13/lib/abstract_controller/
rendering.rb: 110:in `_render_template'
…onpack-3.2.13/lib/action_controller/metal/
streaming.rb: 225:in `_render_template'
…actionpack-3.2.13/lib/abstract_controller/
rendering.rb: 103:in `render_to_body'
…onpack-3.2.13/lib/action_controller/metal/
renderers.rb:  28:in `render_to_body'
…ck-3.2.13/lib/action_controller/metal/
compatibility.rb:  50:in `render_to_body'
…actionpack-3.2.13/lib/abstract_controller/
rendering.rb:  88:in `render'
…onpack-3.2.13/lib/action_controller/metal/
rendering.rb:  16:in `render'
…-3.2.13/lib/action_controller/metal/
instrumentation.rb:  40:in `block (2 levels) in render'
…upport-3.2.13/lib/active_support/core_ext/
benchmark.rb:   5:in `block in ms'
     /app/vendor/ruby-2.1.5/lib/ruby/2.1.0/
benchmark.rb: 294:in `realtime'
…upport-3.2.13/lib/active_support/core_ext/
benchmark.rb:   5:in `ms'
…-3.2.13/lib/action_controller/metal/
instrumentation.rb:  40:in `block in render'
…-3.2.13/lib/action_controller/metal/
instrumentation.rb:  83:in `cleanup_view_runtime'
….2.13/lib/active_record/railties/
controller_runtime.rb:  24:in `cleanup_view_runtime'
…-3.2.13/lib/action_controller/metal/
instrumentation.rb:  39:in `render'
…-3.2.13/lib/action_controller/metal/
implicit_render.rb:  10:in `default_render'
…-3.2.13/lib/action_controller/metal/
implicit_render.rb:   5:in `send_action'
…gems/actionpack-3.2.13/lib/abstract_controller/
base.rb: 167:in `process_action'
…onpack-3.2.13/lib/action_controller/metal/
rendering.rb:  10:in `process_action'
…actionpack-3.2.13/lib/abstract_controller/
callbacks.rb:  18:in `block in process_action'
…s/activesupport-3.2.13/lib/active_support/
callbacks.rb: 480:in `_run__2483185910587203171__process_action__1943234892575870584__callbacks'
…s/activesupport-3.2.13/lib/active_support/
callbacks.rb: 405:in `__run_callback'
…s/activesupport-3.2.13/lib/active_support/
callbacks.rb: 385:in `_run_process_action_callbacks'
…s/activesupport-3.2.13/lib/active_support/
callbacks.rb:  81:in `run_callbacks'
…actionpack-3.2.13/lib/abstract_controller/
callbacks.rb:  17:in `process_action'
…ctionpack-3.2.13/lib/action_controller/metal/
rescue.rb:  29:in `process_action'
…-3.2.13/lib/action_controller/metal/
instrumentation.rb:  30:in `block in process_action'
…tivesupport-3.2.13/lib/active_support/
notifications.rb: 123:in `block in instrument'
….2.13/lib/active_support/notifications/
instrumenter.rb:  20:in `instrument'
…tivesupport-3.2.13/lib/active_support/
notifications.rb: 123:in `instrument'
…-3.2.13/lib/action_controller/metal/
instrumentation.rb:  29:in `process_action'
…k-3.2.13/lib/action_controller/metal/
params_wrapper.rb: 207:in `process_action'
….2.13/lib/active_record/railties/
controller_runtime.rb:  18:in `process_action'
…gems/actionpack-3.2.13/lib/abstract_controller/
base.rb: 121:in `process'
…actionpack-3.2.13/lib/abstract_controller/
rendering.rb:  45:in `process'
…/gems/actionpack-3.2.13/lib/action_controller/
metal.rb: 203:in `dispatch'
…-3.2.13/lib/action_controller/metal/
rack_delegation.rb:  14:in `dispatch'
…/gems/actionpack-3.2.13/lib/action_controller/
metal.rb: 246:in `block in action'
…onpack-3.2.13/lib/action_dispatch/routing/
route_set.rb:  73:in `call'
…onpack-3.2.13/lib/action_dispatch/routing/
route_set.rb:  73:in `dispatch'
…onpack-3.2.13/lib/action_dispatch/routing/
route_set.rb:  36:in `call'
…le/ruby/2.1.0/gems/journey-1.0.4/lib/journey/
router.rb:  68:in `block in call'
…le/ruby/2.1.0/gems/journey-1.0.4/lib/journey/
router.rb:  56:in `each'
…le/ruby/2.1.0/gems/journey-1.0.4/lib/journey/
router.rb:  56:in `call'
…onpack-3.2.13/lib/action_dispatch/routing/
route_set.rb: 612:in `call'
…uby/2.1.0/gems/omniauth-1.1.4/lib/omniauth/
strategy.rb: 184:in `call!'
…uby/2.1.0/gems/omniauth-1.1.4/lib/omniauth/
strategy.rb: 164:in `call'
…ruby/2.1.0/gems/omniauth-1.1.4/lib/omniauth/
builder.rb:  49:in `call'
…-rails-0.4.1/lib/jquery/fileupload/rails/
middleware.rb:  14:in `_call'
…-rails-0.4.1/lib/jquery/fileupload/rails/
middleware.rb:  10:in `call'
…b/action_dispatch/middleware/
best_standards_support.rb:  17:in `call'
…dor/bundle/ruby/2.1.0/gems/rack-1.4.5/lib/rack/
etag.rb:  23:in `call'
…/ruby/2.1.0/gems/rack-1.4.5/lib/rack/
conditionalget.rb:  25:in `call'
…tionpack-3.2.13/lib/action_dispatch/middleware/
head.rb:  14:in `call'
…3.2.13/lib/action_dispatch/middleware/
params_parser.rb:  21:in `call'
…ionpack-3.2.13/lib/action_dispatch/middleware/
flash.rb: 242:in `call'
…/2.1.0/gems/rack-1.4.5/lib/rack/session/abstract/
id.rb: 210:in `context'
…/2.1.0/gems/rack-1.4.5/lib/rack/session/abstract/
id.rb: 205:in `call'
…npack-3.2.13/lib/action_dispatch/middleware/
cookies.rb: 341:in `call'
…s/activerecord-3.2.13/lib/active_record/
query_cache.rb:  64:in `call'
…record/connection_adapters/abstract/
connection_pool.rb: 479:in `call'
…ack-3.2.13/lib/action_dispatch/middleware/
callbacks.rb:  28:in `block in call'
…s/activesupport-3.2.13/lib/active_support/
callbacks.rb: 405:in `_run__3795839754687810954__call__2793300758496312964__callbacks'
…s/activesupport-3.2.13/lib/active_support/
callbacks.rb: 405:in `__run_callback'
…s/activesupport-3.2.13/lib/active_support/
callbacks.rb: 385:in `_run_call_callbacks'
…s/activesupport-3.2.13/lib/active_support/
callbacks.rb:  81:in `run_callbacks'
…ack-3.2.13/lib/action_dispatch/middleware/
callbacks.rb:  27:in `call'
…ack-3.2.13/lib/action_dispatch/middleware/
remote_ip.rb:  31:in `call'
….13/lib/action_dispatch/middleware/
debug_exceptions.rb:  16:in `call'
…2.13/lib/action_dispatch/middleware/
show_exceptions.rb:  56:in `call'
…by/2.1.0/gems/railties-3.2.13/lib/rails/rack/
logger.rb:  32:in `call_app'
…by/2.1.0/gems/railties-3.2.13/lib/rails/rack/
logger.rb:  18:in `call'

**Comment by scudco** [comment]
It looks like this is probably related to #75 

Can you try upgrading to 2.0.1?

**Comment by rafrafgit** [comment]
I upgraded to 2.0.1. Now I got this error instead:
Error message
ActionView::Template::Error: Could not find Country with string 'A2'

Stack trace (show Rails)
…y_select-d3ba0b99beac/lib/country_select/
tag_helper.rb:  80:in `block (2 levels) in country_options_for'
…y_select-d3ba0b99beac/lib/country_select/
tag_helper.rb:  69:in `map'
…y_select-d3ba0b99beac/lib/country_select/
tag_helper.rb:  69:in `block in country_options_for'
…p/vendor/bundle/ruby/2.1.0/gems/i18n-0.6.1/lib/
i18n.rb: 246:in `with_locale'
…y_select-d3ba0b99beac/lib/country_select/
tag_helper.rb:  68:in `country_options_for'
…y_select-d3ba0b99beac/lib/country_select/
tag_helper.rb:  11:in `country_option_tags'
…eac/lib/country_select/rails3/
country_select_helper.rb:  34:in `render'
…eac/lib/country_select/rails3/
country_select_helper.rb:  18:in `country_select'
…le/ruby/2.1.0/gems/journey-1.0.4/lib/journey/
router.rb:  68:in `block in call'
…le/ruby/2.1.0/gems/journey-1.0.4/lib/journey/
router.rb:  56:in `each'
…le/ruby/2.1.0/gems/journey-1.0.4/lib/journey/
router.rb:  56:in `call'

**Comment by scudco** [comment]
Given your stack trace, it looks like you may have specified 'A2' as an entry in the `priority_countries` option.

Can you give me line of code in your template which is calling the country_select helper?

**Comment by rafrafgit** [comment]
ok, that may be the case. I take priority country from IP lookup. 

Controller:
<%
@geoip ||= GeoIP.new("#{Rails.root}/db/GeoIP.dat")  
remote_ip = request.remote_ip 
selected_country = @geoip.country(remote_ip).country_code2
 %>

View:
<% if selected_country %>
        <%= country_select("user", "country", { priority_countries: ["#{selected_country}", "US", "DE", "GB"], locale: "en" }, { selected: selected_country, class: 'form-control', required: 'true', id: 'billing-country'  }) %>    
<% else %>
        <%= country_select("user", "country", { priority_countries: ["US", "DE", "GB"], locale: "en" }, { class: 'form-control', required: 'true', id: 'billing-country' }) %>  
 <% end %>

**Comment by scudco** [comment]
Ah, so here's what you should do, validate that the `selected_country` is a valid code by testing it by creating an instance of `ISO3166::Country`

```erb
<% if selected_country = ISO3166::Country.new(selected_country) %>
  <%= country_select("user", "country", { priority_countries: ["#{selected_country}", "US", "DE", "GB"], locale: "en" }, { selected: selected_country, class: 'form-control', required: 'true', id: 'billing-country' }) %>
<% else %>
  <%= country_select("user", "country", { priority_countries: ["US", "DE", "GB"], locale: "en" }, { class: 'form-control', required: 'true', id: 'billing-country' }) %>
<% end %>
```

Alternatively, you can rescue `CountySelect::CountryNotFoundError` and do the appropriate thing from there.

As a sidenote, I'd be curious to know why `GeoIP` is returning a country code of `A2`.

**Comment by rafrafgit** [comment]
Thanks for your help!
