### ISSUE TITLE
Missing git tags for 1.2.0, 1.3.0 and 1.3.1

### ISSUE THREAD

**Issue by aprescott** [stefanpenner/country_select#88]
Based on https://rubygems.org/gems/country_select/versions and the list of available tags on the GitHub project, tags are missing for versions 1.2.0, 1.3.0 and 1.3.1. This makes it a little confusing when trying to see which versions are available from within GitHub, or when you want to jump to a historical snapshot of the codebase.

Any chance of tagging the older versions?

![screen shot 2014-12-30 at 18 01 41](https://cloud.githubusercontent.com/assets/342081/5583900/117a033e-904e-11e4-9298-f36a788172da.png)

**Comment by scudco** [comment]
Fixed and pushed, thank you for finding the relevant commits :+1:

**Comment by aprescott** [comment]
Thanks! :sparkles:
