### ISSUE TITLE
Gem's Country class conflicts with Country model

### ISSUE THREAD

**Issue by anujaware** [stefanpenner/country_select#89]

**Comment by scudco** [comment]
Can you provide a stack trace or something that could give a little context around this problem?

**Comment by scudco** [comment]
Closing this from inactivity.

**Comment by bitcoder** [comment]
we're also having the same problem, that arises if you have an AR model named Country.

**Comment by scudco** [comment]
Can you provide a stack trace or more information? Which version are you running?

**Comment by bitcoder** [comment]
this has been somehow fixed meanwhile because this does not happen with latest version of countries and country_select. may close it.
it seems that countries was requiring countries/global helper and therefore making Country class seen everywhere
