### ISSUE TITLE
country_select with nil name still render a name

### ISSUE THREAD

**Issue by sirwolfgang** [stefanpenner/country_select#96]
I have a stripe powered form, most of the fields are presented without name as expected. `country_select` however insert empty brackets for its name, causing it to get pulled up.

```erb
<%= country_select nil, nil, { selected: 'US' }, { 'data-stripe' => 'address_country', autocomplete: 'billing country', class: 'country form-control', required: true } %>
```
```html
<select data-stripe="address_country" autocomplete="billing country" class="country form-control" required="required" name="[]" id="_" data-bv-field="[]"></select>
```

**Comment by scudco** [comment]
This seems to represent a pretty good use case for bringing back access to the helper that produces just the option tags or the options array, at least.

For now, I'd recommend you not use country_select and rely on generating the options from the countries gem.

**Comment by scudco** [comment]
Here's how you can get around this right now and still use country_select

```erb
<%= country_select nil, nil, { selected: 'US' }, { 'data-stripe' => 'address_country', autocomplete: 'billing country', class: 'country form-control', required: true, id: nil, name: nil } %>
```

I've just added `name: nil` and `id: nil`

**Comment by scudco** [comment]
I think this should be fixed in a future version, but it's going to take some time to dig into why it's generating `[]` for name.
