### ISSUE TITLE
Priority countries appearing twice in the country drop-down

### ISSUE THREAD

**Issue by toncid** [stefanpenner/country_select#98]
For some reason, priority countries are appearing twice in the drop-down: once in the priority section and later among all countries. Not sure if this is intended behavior.

Thoughts?

**Comment by scudco** [comment]
That is the intended behavior currently and [there are tests](https://github.com/stefanpenner/country_select/blob/ff1092ece6cb87a6781cccd47f5a6f4a45b1e8b2/spec/country_select_spec.rb#L80-L85) that make sure the first one is the selected one. Are you  running into problems with it generating two identical `option` tags?

**Comment by toncid** [comment]
Not really, I just didn't expect that - it's fine. Thanks!
